name=Stereoscopic
version=${version}
additionalVersions=
className=com.mitchellmarx.stereoscopic.loading.rfb.StereoscopicRfbPlugin
transformerExclusions=com.mitchellmarx.stereoscopic.transformer
versionConstraints=
loadBefore=
loadAfter=mixin; lwjgl3ify
loadRequires=
